pages:
 # key is the dirname of pages in src/pages
 home:
  # 首页配置
  zh-cn:
   title: 'ServerlessDevs'
   keywords: 'ServerlessDevs,serverless,阿里云函数计算'
   description: 'ServerlessDevs 首页'
  # home config
  en-us:
   title: 'ServerlessDevs'
   keywords: 'ServerlessDevs,serverless,阿里云函数计算'
   description: 'ServerlessDevs 首页'
 products:
  # 产品页
  zh-cn:
   title: 'ServerlessDevs 产品页'
   keywords: 'ServerlessDevs,serverless,阿里云函数计算,ServerlessDesktop'
   description: 'ServerlessDevs 产品页'
  # home config
  en-us:
   title: 'ServerlessDevs 产品页'
   keywords: 'ServerlessDevs,serverless,阿里云函数计算'
   description: 'ServerlessDevs 产品页'
 doc:
  # 文档页
  zh-cn:
   title: 'ServerlessDevs 文档页'
   keywords: 'ServerlessDevs,serverless,阿里云函数计算'
   description: 'ServerlessDevs 文档页'
  # home config
  en-us:
   title: 'ServerlessDevs 文档页'
   keywords: 'ServerlessDevs,serverless,阿里云函数计算'
   description: 'ServerlessDevs 文档页'
 community:
  # 社区页配置
  zh-cn:
   title: '网页标签title'
   keywords: '关键词1，关键词2'
   description: '页面内容简介'
  # community page config
  en-us:
   title: 'page title'
   keywords: 'keyword1,keyword2'
   description: 'page description'
 blog:
  # 博客列表页配置
  zh-cn:
   title: 'ServerlessDevs 博客'
   keywords: 'ServerlessDevs,serverless,阿里云函数计算，博客'
   description: 'ServerlessDevs 博客'
  en-us:
   # blog list page config
   title: 'ServerlessDevs 博客'
   keywords: 'ServerlessDevs,serverless,阿里云函数计算，博客'
   description: 'ServerlessDevs 博客'
 desktop:
  # desktop配置
  zh-cn:
   title: 'ServerlessDesktop'
   keywords: 'ServerlessDevs,serverless,阿里云函数计算，electron'
   description: 'ServerlessDevs 桌面应用'
  en-us:
   # blog list page config
   title: 'ServerlessDevs 博客'
   keywords: 'ServerlessDevs,serverless,阿里云函数计算，electron'
   description: 'ServerlessDevs 桌面应用'
 cli:
  # cli配置
  zh-cn:
   title: 'ServerlessDevs Cli'
   keywords: 'ServerlessDevs,serverless,阿里云函数计算，cli'
   description: 'ServerlessDevs 交互式命令行'
  en-us:
   # blog list page config
   title: 'ServerlessDevs Cli'
   keywords: 'ServerlessDevs,serverless,阿里云函数计算，cli'
   description: 'ServerlessDevs 交互式命令行'